source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'cancan'
gem 'devise'
gem 'simple_form'
gem 'inherited_resources'
gem 'haml'
gem 'compass'
gem 'paperclip'
gem 'jquery-rails'
gem 'mysql2'
gem 'hoptoad_notifier'
gem 'newrelic_rpm'
gem 'i18n-js'

group :development, :test do
  gem 'hpricot'
  gem 'ruby_parser'
  gem 'capistrano'
  gem 'capistrano-ext'
  gem 'fuubar'
  gem 'webrat'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'cucumber'
  gem 'shoulda'
  gem 'rspec-rails', "~> 2.1.0"
  gem 'mocha'
end